artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  bucket_name: smoke_detection
  source_blob_name: smoke_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion