artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  bucket_name: smoke_detection
  source_blob_name: smoke_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.keras
  updated_base_model_path: artifacts/base_model/base_model_updated.keras


callbacks:
  root_dir: artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/callbacks/checkpoint_dir/model.keras


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/trained_model.keras
  base_model_path: artifacts/base_model/base_model_updated.keras
  train_path: artifacts/data_ingestion/smoke_data/Training/Training
  test_path: artifacts/data_ingestion/smoke_data/Testing/Testing
  valid_path: artifacts/data_ingestion/smoke_data/Validation/Validation

evaluation:
  model_path: artifacts/training/trained_model.keras
  test_path: artifacts/data_ingestion/smoke_data/Testing/Testing

